<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitaee52b044f5f5701618bdb98672ec98f
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitaee52b044f5f5701618bdb98672ec98f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitaee52b044f5f5701618bdb98672ec98f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitaee52b044f5f5701618bdb98672ec98f::$classMap;

        }, null, ClassLoader::class);
    }
}
